name: "Check Alembic Migrations and Generate SQL"
description: "Checks for Alembic migrations in a pull request, generates SQL for the specified dialect, and adds it as a PR comment"

# Note: This action requires the following permissions:
# - contents: read
# - pull-requests: write

inputs:
  dialect:
    description: "SQL dialect to use for Alembic (postgresql, mysql, etc.)"
    required: true
    default: "postgresql"
  alembic_ini:
    description: "Path to alembic.ini file"
    required: true
    default: "alembic.ini"
  migration_path:
    description: "Path to Alembic migrations directory"
    required: true
    default: "migrations"
  database:
    description: "Database name for multi-database setup (optional)"
    required: false
  revision_range:
    description: "Optional revision range for SQL generation (e.g., 'head:base')"
    required: false
    default: "head"
  pr_revisions_only:
    description: "Only generate SQL for migrations in the current PR (true/false)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Create virtual environment and install dependencies
      shell: bash
      run: |
        uv venv
        uv pip install alembic sqlalchemy

    - name: Check for Alembic migrations
      id: check_migrations
      shell: bash
      run: |
        DATABASE_ARG=""
        if [ -n "${{ inputs.database }}" ]; then
          DATABASE_ARG="--database ${{ inputs.database }}"
        fi
        uv run python ${{ github.action_path }}/../shared/scripts/generate_sql.py --check-migrations --migration-path ${{ inputs.migration_path }} $DATABASE_ARG --verbose

    - name: Generate SQL from Alembic migrations
      if: steps.check_migrations.outputs.has_migrations == 'true'
      id: generate_sql
      shell: bash
      run: |
        # Add pr-revisions-only parameter conditionally
        PR_ONLY=""
        if [ "${{ inputs.pr_revisions_only }}" = "true" ]; then
          PR_ONLY="--pr-revisions-only"
        fi

        DATABASE_ARG=""
        if [ -n "${{ inputs.database }}" ]; then
          DATABASE_ARG="--database ${{ inputs.database }}"
        fi

        uv run python ${{ github.action_path }}/../shared/scripts/generate_sql.py --generate-sql \
          --dialect ${{ inputs.dialect }} \
          --alembic-ini ${{ inputs.alembic_ini }} \
          --migration-path ${{ inputs.migration_path }} \
          --revision-range ${{ inputs.revision_range }} \
          $DATABASE_ARG \
          $PR_ONLY \
          --verbose

    - name: Add SQL to PR comment
      if: steps.check_migrations.outputs.has_migrations == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          // Unique marker to identify our comment
          const COMMENT_MARKER = '<!-- alembic-actions-sql-comment -->';
          const dialect = process.env.DIALECT || '${{ inputs.dialect }}';
          const database = process.env.DATABASE || '';
          const databaseMarker = database ? `-${database}` : '';
          const fullMarker = `${COMMENT_MARKER}${databaseMarker}`;

          // Read the generated SQL
          const sqlPath = path.join(process.env.GITHUB_WORKSPACE, 'generated.sql');

          // Check if file exists
          if (!fs.existsSync(sqlPath)) {
            console.log('No generated.sql file found, skipping comment');
            return;
          }

          const sql = fs.readFileSync(sqlPath, 'utf8');

          // If SQL is empty, skip adding/updating comment
          if (!sql || sql.trim() === '') {
            console.log('No SQL changes generated, skipping comment');
            return;
          }

          // Get existing comments to find our previous comment
          const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          });

          // Find existing comment with our marker
          const existingComment = comments.find(c => c.body && c.body.includes(fullMarker));

          // Prepare the comment body
          const databaseInfo = database ? `\n**Database**: \`${database}\`\n` : '';
          const commentBody = fullMarker + "\n" +
                              "## SQL Generated from Alembic Migrations\n\n" +
                              "**Dialect**: `" + dialect + "`" + databaseInfo + "\n" +
                              "```sql\n" +
                              sql + "\n" +
                              "```\n\n" +
                              "*This SQL was automatically generated by the [alembic-actions](https://github.com/OpenMindUA/alembic-actions) GitHub Action*";

          if (existingComment) {
            // Extract SQL from existing comment for comparison
            const sqlRegex = /```sql\n([\s\S]*?)\n```/;
            const existingMatch = existingComment.body.match(sqlRegex);
            const existingSql = existingMatch ? existingMatch[1] : '';

            // Only update if SQL has changed
            if (existingSql.trim() === sql.trim()) {
              console.log('SQL unchanged from previous comment, skipping update');
              return;
            }

            // Update existing comment
            console.log('SQL changed, updating existing comment');
            await github.rest.issues.updateComment({
              comment_id: existingComment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
          } else {
            // Create new comment
            console.log('Creating new SQL comment');
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
          }
      env:
        DIALECT: ${{ inputs.dialect }}
        DATABASE: ${{ inputs.database }}
